apiVersion: batch/v1
kind: Job
metadata:
  name: dbmigrate
spec:
  template:
    spec:
      containers: 
      - name: dbmigrate
        image: nyuappsec/assign3:v0
        command: ["python3",  "manage.py", "migrate"]
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: custom-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DB
              value: GiftcardSiteDB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"

            - name: ADMIN_UNAME
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: username

            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: password

            - name: secretkey
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: secretkey

      restartPolicy: Never
  backoffLimit: 4
