apiVersion: batch/v1
kind: Job
metadata:
  name: dbseeder
spec:
  template:
    spec:
      containers: 
      - name: dbseeder
        image: nyuappsec/assign3-db:v0
        command: ["/bin/sh"]
        args: ["-c", "mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --database=${MYSQL_DATABASE} --host=mysql-service -f < /docker-entrypoint-initdb.d/seed.sql"]
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: custom-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: GiftcardSiteDB

      restartPolicy: Never
  backoffLimit: 4


